apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  {{- if .Values.ingress.alb }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: my-ingress-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-north-1:677673473760:certificate/a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
  {{- end }}
spec:
  {{- if .Values.ingress.alb }}
  ingressClassName: alb
  {{- else }}
  ingressClassName: nginx
  {{- end }}
  rules:
    {{- if not .Values.ingress.alb }}
    - host: jobber.local
      http:
        paths:
          - path: /jobs
            pathType: Prefix
            backend:
              service:
                name: jobs-http
                port:
                  number: {{ .Values.jobs.port.http }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-http
                port:
                  number: {{ .Values.auth.port.http }}
    {{- else }}
    - http:
        paths:
          - path: /jobs
            pathType: Prefix
            backend:
              service:
                name: jobs-http
                port:
                  number: {{ .Values.jobs.port.http }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-http
                port:
                  number: {{ .Values.auth.port.http }}
    {{- end }}