{{- if .Values.products.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.products.port.grpc }}
      targetPort: {{ .Values.products.port.grpc }}
  selector:
    app: products
{{- end }}