services:
  postgres:
    image: postgres:latest
    container_name: jobber_auth_postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: jobber_auth
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: jobber_auth_pgadmin
    ports:
      - 5433:80
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  pulsar:
    image: apachepulsar/pulsar:latest
    command: >
      /pulsar/bin/pulsar standalone
    ports:
      - 6650:6650
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
