// Auto-generated by scripts/proto-generate-ts.mjs from `package` in each .proto file.
// Nest registration tokens: ts-proto omits these when exportCommonSymbols=false.

export const AUTH_PACKAGE_NAME = 'auth';
export const PRODUCTS_PACKAGE_NAME = 'products';
