'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const tslib_1 = require('tslib');
// Auto-generated by scripts/proto-generate-ts.mjs. Do not edit manually.
tslib_1.__exportStar(require('./generated/proto/auth'), exports);
//# sourceMappingURL=index.js.map
